react-dom is external peerDependency, just like react. (#1067)
fixes version conflicts, e.g. I got an error

  Uncaught TypeError: this.updater.enqueueCallback is not a function when using setState callback

because I use React 16.x and react-jsonschema-form bundled react-dom 15.x

See https://github.com/facebook/react/issues/10320#issuecomment-318754280